//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuji.RISLite.Entidades.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class RISLiteEntities : DbContext
    {
        public RISLiteEntities()
            : base("name=RISLiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_CAT_TipoMensaje> tbl_CAT_TipoMensaje { get; set; }
        public DbSet<tbl_MST_Bitacora> tbl_MST_Bitacora { get; set; }
        public DbSet<tbl_CAT_TipoUsuario> tbl_CAT_TipoUsuario { get; set; }
        public DbSet<tbl_CAT_Usuario> tbl_CAT_Usuario { get; set; }
        public DbSet<tbl_CAT_Catalogo> tbl_CAT_Catalogo { get; set; }
        public DbSet<tbl_CAT_Modalidad> tbl_CAT_Modalidad { get; set; }
        public DbSet<tbl_CAT_EstatusCita> tbl_CAT_EstatusCita { get; set; }
        public DbSet<tbl_CAT_EstatusEstudio> tbl_CAT_EstatusEstudio { get; set; }
        public DbSet<tbl_CAT_Genero> tbl_CAT_Genero { get; set; }
        public DbSet<tbl_CAT_InstitucionProcedencia> tbl_CAT_InstitucionProcedencia { get; set; }
        public DbSet<tbl_CAT_TipoMovimiento> tbl_CAT_TipoMovimiento { get; set; }
        public DbSet<tbl_CAT_Botones> tbl_CAT_Botones { get; set; }
        public DbSet<tbl_CAT_Vistas> tbl_CAT_Vistas { get; set; }
        public DbSet<tbl_REL_BotonVista> tbl_REL_BotonVista { get; set; }
        public DbSet<tbl_REL_TipoUsuarioBoton> tbl_REL_TipoUsuarioBoton { get; set; }
        public DbSet<tbl_MST_Paciente> tbl_MST_Paciente { get; set; }
        public DbSet<tbl_CONFIG_VariablesAdiPaciente> tbl_CONFIG_VariablesAdiPaciente { get; set; }
        public DbSet<tbl_DET_PacienteDinamico> tbl_DET_PacienteDinamico { get; set; }
        public DbSet<tbl_MST_ConfiguracionSistema> tbl_MST_ConfiguracionSistema { get; set; }
        public DbSet<tbl_Conf_CorreoSitio> tbl_Conf_CorreoSitio { get; set; }
        public DbSet<tbl_CONFIG_VariablesAdiCita> tbl_CONFIG_VariablesAdiCita { get; set; }
        public DbSet<tbl_CAT_Prestacion> tbl_CAT_Prestacion { get; set; }
        public DbSet<tbl_REL_ModalidadPrestacion> tbl_REL_ModalidadPrestacion { get; set; }
        public DbSet<tbl_CAT_Equipo> tbl_CAT_Equipo { get; set; }
        public DbSet<tbl_CAT_CodigoPostal> tbl_CAT_CodigoPostal { get; set; }
        public DbSet<tbl_CAT_Estado> tbl_CAT_Estado { get; set; }
        public DbSet<tbl_CAT_Identificacion> tbl_CAT_Identificacion { get; set; }
        public DbSet<tbl_CAT_Municipio> tbl_CAT_Municipio { get; set; }
        public DbSet<tbl_DET_DireccionPaciente> tbl_DET_DireccionPaciente { get; set; }
        public DbSet<tbl_DET_Paciente> tbl_DET_Paciente { get; set; }
        public DbSet<tbl_MST_Cita> tbl_MST_Cita { get; set; }
        public DbSet<tbl_REL_IdentificacionPaciente> tbl_REL_IdentificacionPaciente { get; set; }
        public DbSet<tbl_REL_PacienteCita> tbl_REL_PacienteCita { get; set; }
    
        public virtual ObjectResult<stp_getListCatalogo_Result> stp_getListCatalogo(Nullable<int> intCatalogoID)
        {
            var intCatalogoIDParameter = intCatalogoID.HasValue ?
                new ObjectParameter("intCatalogoID", intCatalogoID) :
                new ObjectParameter("intCatalogoID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<stp_getListCatalogo_Result>("stp_getListCatalogo", intCatalogoIDParameter);
        }
    
        public virtual ObjectResult<stp_updateCatEstatus_Result> stp_updateCatEstatus(Nullable<int> intCatalogoID, Nullable<bool> bitActivo, Nullable<int> intPrimaryKey)
        {
            var intCatalogoIDParameter = intCatalogoID.HasValue ?
                new ObjectParameter("intCatalogoID", intCatalogoID) :
                new ObjectParameter("intCatalogoID", typeof(int));
    
            var bitActivoParameter = bitActivo.HasValue ?
                new ObjectParameter("bitActivo", bitActivo) :
                new ObjectParameter("bitActivo", typeof(bool));
    
            var intPrimaryKeyParameter = intPrimaryKey.HasValue ?
                new ObjectParameter("intPrimaryKey", intPrimaryKey) :
                new ObjectParameter("intPrimaryKey", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<stp_updateCatEstatus_Result>("stp_updateCatEstatus", intCatalogoIDParameter, bitActivoParameter, intPrimaryKeyParameter);
        }
    
        public virtual ObjectResult<stp_setItemCatalogo_Result> stp_setItemCatalogo(Nullable<int> intCatalogoID, string vchValor, string vchUserAdmin)
        {
            var intCatalogoIDParameter = intCatalogoID.HasValue ?
                new ObjectParameter("intCatalogoID", intCatalogoID) :
                new ObjectParameter("intCatalogoID", typeof(int));
    
            var vchValorParameter = vchValor != null ?
                new ObjectParameter("vchValor", vchValor) :
                new ObjectParameter("vchValor", typeof(string));
    
            var vchUserAdminParameter = vchUserAdmin != null ?
                new ObjectParameter("vchUserAdmin", vchUserAdmin) :
                new ObjectParameter("vchUserAdmin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<stp_setItemCatalogo_Result>("stp_setItemCatalogo", intCatalogoIDParameter, vchValorParameter, vchUserAdminParameter);
        }
    
        public virtual ObjectResult<stp_updateCatalogo_Result> stp_updateCatalogo(Nullable<int> intCatalogoID, Nullable<int> intPrimaryKey, string vchValor)
        {
            var intCatalogoIDParameter = intCatalogoID.HasValue ?
                new ObjectParameter("intCatalogoID", intCatalogoID) :
                new ObjectParameter("intCatalogoID", typeof(int));
    
            var intPrimaryKeyParameter = intPrimaryKey.HasValue ?
                new ObjectParameter("intPrimaryKey", intPrimaryKey) :
                new ObjectParameter("intPrimaryKey", typeof(int));
    
            var vchValorParameter = vchValor != null ?
                new ObjectParameter("vchValor", vchValor) :
                new ObjectParameter("vchValor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<stp_updateCatalogo_Result>("stp_updateCatalogo", intCatalogoIDParameter, intPrimaryKeyParameter, vchValorParameter);
        }
    
        public virtual ObjectResult<stp_getListaPaginas_Result> stp_getListaPaginas(Nullable<int> intTipoUsuarioID)
        {
            var intTipoUsuarioIDParameter = intTipoUsuarioID.HasValue ?
                new ObjectParameter("intTipoUsuarioID", intTipoUsuarioID) :
                new ObjectParameter("intTipoUsuarioID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<stp_getListaPaginas_Result>("stp_getListaPaginas", intTipoUsuarioIDParameter);
        }
    
        public virtual ObjectResult<stp_getPrestacionModalidad_Result> stp_getPrestacionModalidad(Nullable<int> intModalidadId)
        {
            var intModalidadIdParameter = intModalidadId.HasValue ?
                new ObjectParameter("intModalidadId", intModalidadId) :
                new ObjectParameter("intModalidadId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<stp_getPrestacionModalidad_Result>("stp_getPrestacionModalidad", intModalidadIdParameter);
        }
    
        public virtual ObjectResult<stp_getBusquedaPaciente_Result> stp_getBusquedaPaciente(string vchCadena)
        {
            var vchCadenaParameter = vchCadena != null ?
                new ObjectParameter("vchCadena", vchCadena) :
                new ObjectParameter("vchCadena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<stp_getBusquedaPaciente_Result>("stp_getBusquedaPaciente", vchCadenaParameter);
        }
    }
}
