//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuji.RISLite.Entidades.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RISLiteEntities : DbContext
    {
        public RISLiteEntities()
            : base("name=RISLiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_CAT_TipoMensaje> tbl_CAT_TipoMensaje { get; set; }
        public DbSet<tbl_MST_Bitacora> tbl_MST_Bitacora { get; set; }
        public DbSet<tbl_CAT_TipoUsuario> tbl_CAT_TipoUsuario { get; set; }
        public DbSet<tbl_CAT_Usuario> tbl_CAT_Usuario { get; set; }
        public DbSet<tbl_CAT_Catalogo> tbl_CAT_Catalogo { get; set; }
    }
}
