//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuji.RISLite.Entidades.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CAT_Sitio
    {
        public tbl_CAT_Sitio()
        {
            this.tbl_CONFIG_VariablesAdiPaciente = new HashSet<tbl_CONFIG_VariablesAdiPaciente>();
            this.tbl_CAT_Identificacion = new HashSet<tbl_CAT_Identificacion>();
            this.tbl_CAT_Usuario = new HashSet<tbl_CAT_Usuario>();
            this.tbl_MST_ConfiguracionSistema = new HashSet<tbl_MST_ConfiguracionSistema>();
            this.tbl_Conf_CorreoSitio = new HashSet<tbl_Conf_CorreoSitio>();
            this.tbl_CONFIG_VariablesAdiCita = new HashSet<tbl_CONFIG_VariablesAdiCita>();
            this.tbl_CAT_InstitucionProcedencia = new HashSet<tbl_CAT_InstitucionProcedencia>();
            this.tbl_CAT_MedicoTratante = new HashSet<tbl_CAT_MedicoTratante>();
            this.tbl_CAT_Modalidad = new HashSet<tbl_CAT_Modalidad>();
            this.tbl_CAT_Prestacion = new HashSet<tbl_CAT_Prestacion>();
            this.tbl_CAT_Equipo = new HashSet<tbl_CAT_Equipo>();
            this.tbl_MST_Adicionales = new HashSet<tbl_MST_Adicionales>();
            this.tbl_REL_SitioPaciente = new HashSet<tbl_REL_SitioPaciente>();
            this.tbl_CONFIG_Agenda = new HashSet<tbl_CONFIG_Agenda>();
            this.tbl_CAT_HoraMuerta = new HashSet<tbl_CAT_HoraMuerta>();
            this.tbl_CAT_DiaFeriado = new HashSet<tbl_CAT_DiaFeriado>();
        }
    
        public int intSitioID { get; set; }
        public string vchNombreSitio { get; set; }
        public Nullable<bool> bitActivo { get; set; }
        public Nullable<System.DateTime> datFecha { get; set; }
        public string vchUserAdmin { get; set; }
    
        public virtual ICollection<tbl_CONFIG_VariablesAdiPaciente> tbl_CONFIG_VariablesAdiPaciente { get; set; }
        public virtual ICollection<tbl_CAT_Identificacion> tbl_CAT_Identificacion { get; set; }
        public virtual ICollection<tbl_CAT_Usuario> tbl_CAT_Usuario { get; set; }
        public virtual ICollection<tbl_MST_ConfiguracionSistema> tbl_MST_ConfiguracionSistema { get; set; }
        public virtual ICollection<tbl_Conf_CorreoSitio> tbl_Conf_CorreoSitio { get; set; }
        public virtual ICollection<tbl_CONFIG_VariablesAdiCita> tbl_CONFIG_VariablesAdiCita { get; set; }
        public virtual ICollection<tbl_CAT_InstitucionProcedencia> tbl_CAT_InstitucionProcedencia { get; set; }
        public virtual ICollection<tbl_CAT_MedicoTratante> tbl_CAT_MedicoTratante { get; set; }
        public virtual ICollection<tbl_CAT_Modalidad> tbl_CAT_Modalidad { get; set; }
        public virtual ICollection<tbl_CAT_Prestacion> tbl_CAT_Prestacion { get; set; }
        public virtual ICollection<tbl_CAT_Equipo> tbl_CAT_Equipo { get; set; }
        public virtual ICollection<tbl_MST_Adicionales> tbl_MST_Adicionales { get; set; }
        public virtual ICollection<tbl_REL_SitioPaciente> tbl_REL_SitioPaciente { get; set; }
        public virtual ICollection<tbl_CONFIG_Agenda> tbl_CONFIG_Agenda { get; set; }
        public virtual ICollection<tbl_CAT_HoraMuerta> tbl_CAT_HoraMuerta { get; set; }
        public virtual ICollection<tbl_CAT_DiaFeriado> tbl_CAT_DiaFeriado { get; set; }
    }
}
