//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuji.RISLite.Entidades.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MST_Estudio
    {
        public tbl_MST_Estudio()
        {
            this.tbl_REL_CitaEstudio = new HashSet<tbl_REL_CitaEstudio>();
        }
    
        public long intEstudioID { get; set; }
        public Nullable<int> intEquipoID { get; set; }
        public Nullable<int> intEstatusEstudio { get; set; }
        public Nullable<int> intRELModPres { get; set; }
        public Nullable<System.DateTime> datFechaInicio { get; set; }
        public Nullable<System.DateTime> datFechaFin { get; set; }
        public string vchTitulo { get; set; }
        public string vchDescripcion { get; set; }
        public Nullable<System.DateTime> datFecha { get; set; }
        public string vchUserAdmin { get; set; }
        public Nullable<bool> bitActivo { get; set; }
    
        public virtual tbl_CAT_EstatusEstudio tbl_CAT_EstatusEstudio { get; set; }
        public virtual tbl_REL_ModalidadPrestacion tbl_REL_ModalidadPrestacion { get; set; }
        public virtual ICollection<tbl_REL_CitaEstudio> tbl_REL_CitaEstudio { get; set; }
    }
}
