//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuji.RISLite.Entidades.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CAT_Usuario
    {
        public tbl_CAT_Usuario()
        {
            this.tbl_REL_ModalidadesTecnico = new HashSet<tbl_REL_ModalidadesTecnico>();
            this.tbl_REL_EstudioTecnico = new HashSet<tbl_REL_EstudioTecnico>();
        }
    
        public int intUsuarioID { get; set; }
        public Nullable<int> intTipoUsuario { get; set; }
        public Nullable<int> intSitioID { get; set; }
        public string vchUsuario { get; set; }
        public string vchNombre { get; set; }
        public string vchEmail { get; set; }
        public Nullable<bool> bitActivo { get; set; }
        public Nullable<System.DateTime> datFecha { get; set; }
        public string vchUserAdmin { get; set; }
        public string vchPassword { get; set; }
        public string vchRutaIcono { get; set; }
    
        public virtual tbl_CAT_Sitio tbl_CAT_Sitio { get; set; }
        public virtual tbl_CAT_TipoUsuario tbl_CAT_TipoUsuario { get; set; }
        public virtual ICollection<tbl_REL_ModalidadesTecnico> tbl_REL_ModalidadesTecnico { get; set; }
        public virtual ICollection<tbl_REL_EstudioTecnico> tbl_REL_EstudioTecnico { get; set; }
    }
}
