//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuji.RISLite.Entidades.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CONFIG_VariablesAdiCita
    {
        public tbl_CONFIG_VariablesAdiCita()
        {
            this.tbl_DET_CitaDinamico = new HashSet<tbl_DET_CitaDinamico>();
        }
    
        public int intVarAdiCitaID { get; set; }
        public Nullable<int> intSitioID { get; set; }
        public string vchNombreVariable { get; set; }
        public Nullable<bool> bitActivo { get; set; }
        public Nullable<System.DateTime> datFecha { get; set; }
        public string vchUserAdmin { get; set; }
    
        public virtual tbl_CAT_Sitio tbl_CAT_Sitio { get; set; }
        public virtual ICollection<tbl_DET_CitaDinamico> tbl_DET_CitaDinamico { get; set; }
    }
}
