//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuji.RISLite.Entidades.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MST_Cita
    {
        public tbl_MST_Cita()
        {
            this.tbl_DET_CitaDinamico = new HashSet<tbl_DET_CitaDinamico>();
            this.tbl_DET_Cita = new HashSet<tbl_DET_Cita>();
        }
    
        public long intCitaID { get; set; }
        public Nullable<int> intMedicoTraID { get; set; }
        public Nullable<int> intInstitucionID { get; set; }
        public Nullable<int> intEstatusCita { get; set; }
        public Nullable<System.DateTime> datFechaCita { get; set; }
        public Nullable<bool> bitActivo { get; set; }
        public Nullable<System.DateTime> datFecha { get; set; }
        public string vchUserAdmin { get; set; }
        public byte[] vbQRImage { get; set; }
    
        public virtual tbl_CAT_EstatusCita tbl_CAT_EstatusCita { get; set; }
        public virtual tbl_CAT_InstitucionProcedencia tbl_CAT_InstitucionProcedencia { get; set; }
        public virtual tbl_CAT_MedicoTratante tbl_CAT_MedicoTratante { get; set; }
        public virtual ICollection<tbl_DET_CitaDinamico> tbl_DET_CitaDinamico { get; set; }
        public virtual ICollection<tbl_DET_Cita> tbl_DET_Cita { get; set; }
    }
}
