//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuji.RISLite.Entidades.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CAT_Identificacion
    {
        public tbl_CAT_Identificacion()
        {
            this.tbl_REL_IdentificacionPaciente = new HashSet<tbl_REL_IdentificacionPaciente>();
        }
    
        public long intIdentificacionID { get; set; }
        public string vchNombreId { get; set; }
        public Nullable<bool> bitActivo { get; set; }
        public Nullable<System.DateTime> datFecha { get; set; }
        public string vchUserAdmin { get; set; }
    
        public virtual ICollection<tbl_REL_IdentificacionPaciente> tbl_REL_IdentificacionPaciente { get; set; }
    }
}
