//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuji.RISLite.Entidades.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CAT_MedicoTratante
    {
        public tbl_CAT_MedicoTratante()
        {
            this.tbl_MST_Cita = new HashSet<tbl_MST_Cita>();
        }
    
        public int intMedicoTraID { get; set; }
        public string vchNombreMedico { get; set; }
        public string vchApellidos { get; set; }
        public Nullable<bool> bitActivo { get; set; }
        public Nullable<System.DateTime> datFecha { get; set; }
        public string vchUserAdmin { get; set; }
    
        public virtual ICollection<tbl_MST_Cita> tbl_MST_Cita { get; set; }
    }
}
