//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuji.RISLite.Entidades.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CAT_CodigoPostal
    {
        public tbl_CAT_CodigoPostal()
        {
            this.tbl_DET_DireccionPaciente = new HashSet<tbl_DET_DireccionPaciente>();
        }
    
        public int intCodigoPostalID { get; set; }
        public Nullable<int> intMunicipioID { get; set; }
        public string vchCodigoPostal { get; set; }
        public string vchColonia { get; set; }
        public Nullable<bool> bitActivo { get; set; }
        public Nullable<System.DateTime> datFecha { get; set; }
        public string vchUserAdmin { get; set; }
    
        public virtual tbl_CAT_Municipio tbl_CAT_Municipio { get; set; }
        public virtual ICollection<tbl_DET_DireccionPaciente> tbl_DET_DireccionPaciente { get; set; }
    }
}
