//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuji.RISLite.Entidades.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MST_Paciente
    {
        public tbl_MST_Paciente()
        {
            this.tbl_DET_PacienteDinamico = new HashSet<tbl_DET_PacienteDinamico>();
            this.tbl_DET_DireccionPaciente = new HashSet<tbl_DET_DireccionPaciente>();
            this.tbl_DET_Paciente = new HashSet<tbl_DET_Paciente>();
            this.tbl_REL_PacienteCita = new HashSet<tbl_REL_PacienteCita>();
            this.tbl_REL_IdentificacionPaciente = new HashSet<tbl_REL_IdentificacionPaciente>();
        }
    
        public long intPacienteID { get; set; }
        public Nullable<int> intGeneroID { get; set; }
        public string vchNombre { get; set; }
        public string vchApellidos { get; set; }
        public Nullable<System.DateTime> datFechaNac { get; set; }
        public Nullable<bool> bitActivo { get; set; }
        public Nullable<System.DateTime> datFecha { get; set; }
        public string vchUserAdmin { get; set; }
    
        public virtual tbl_CAT_Genero tbl_CAT_Genero { get; set; }
        public virtual ICollection<tbl_DET_PacienteDinamico> tbl_DET_PacienteDinamico { get; set; }
        public virtual ICollection<tbl_DET_DireccionPaciente> tbl_DET_DireccionPaciente { get; set; }
        public virtual ICollection<tbl_DET_Paciente> tbl_DET_Paciente { get; set; }
        public virtual ICollection<tbl_REL_PacienteCita> tbl_REL_PacienteCita { get; set; }
        public virtual ICollection<tbl_REL_IdentificacionPaciente> tbl_REL_IdentificacionPaciente { get; set; }
    }
}
