//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuji.RISLite.Entidades.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CAT_Modalidad
    {
        public tbl_CAT_Modalidad()
        {
            this.tbl_REL_ModalidadPrestacion = new HashSet<tbl_REL_ModalidadPrestacion>();
            this.tbl_CAT_Equipo = new HashSet<tbl_CAT_Equipo>();
        }
    
        public int intModalidadID { get; set; }
        public string vchModalidad { get; set; }
        public string vchCodigo { get; set; }
        public Nullable<bool> bitActivo { get; set; }
        public Nullable<System.DateTime> datFecha { get; set; }
        public string vchUserAdmin { get; set; }
        public string vchColor { get; set; }
        public Nullable<int> intDuracionGen { get; set; }
        public Nullable<int> intSitioID { get; set; }
    
        public virtual ICollection<tbl_REL_ModalidadPrestacion> tbl_REL_ModalidadPrestacion { get; set; }
        public virtual tbl_CAT_Sitio tbl_CAT_Sitio { get; set; }
        public virtual ICollection<tbl_CAT_Equipo> tbl_CAT_Equipo { get; set; }
    }
}
