//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuji.RISLite.Entidades.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CONFIG_VariablesAdiPaciente
    {
        public tbl_CONFIG_VariablesAdiPaciente()
        {
            this.tbl_DET_PacienteDinamico = new HashSet<tbl_DET_PacienteDinamico>();
        }
    
        public int intVarAdiPacienteID { get; set; }
        public string vchNombreVariable { get; set; }
        public Nullable<bool> bitActivo { get; set; }
        public Nullable<System.DateTime> datFecha { get; set; }
        public string vchUserAdmin { get; set; }
    
        public virtual ICollection<tbl_DET_PacienteDinamico> tbl_DET_PacienteDinamico { get; set; }
    }
}
