//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuji.RISLite.Entidades.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DET_Paciente
    {
        public long intDETPacienteID { get; set; }
        public Nullable<long> intPacienteID { get; set; }
        public string vchNumeroContacto { get; set; }
        public string vchEmail { get; set; }
        public string vchNombreAcompaniante { get; set; }
        public string vchContactoAcompaniante { get; set; }
        public string vchParentesco { get; set; }
        public Nullable<bool> bitActivo { get; set; }
        public Nullable<System.DateTime> datFecha { get; set; }
        public string vchUserAdmin { get; set; }
    
        public virtual tbl_MST_Paciente tbl_MST_Paciente { get; set; }
    }
}
