//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuji.RISLite.Entidades.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CAT_Municipio
    {
        public tbl_CAT_Municipio()
        {
            this.tbl_CAT_CodigoPostal = new HashSet<tbl_CAT_CodigoPostal>();
        }
    
        public int intMunicipioID { get; set; }
        public Nullable<int> intEstadoID { get; set; }
        public string vchMunicipio { get; set; }
        public Nullable<bool> bitActivo { get; set; }
        public Nullable<System.DateTime> datFecha { get; set; }
        public string vchUserAdmin { get; set; }
    
        public virtual ICollection<tbl_CAT_CodigoPostal> tbl_CAT_CodigoPostal { get; set; }
        public virtual tbl_CAT_Estado tbl_CAT_Estado { get; set; }
    }
}
